### ISSUE TITLE
Errors when `6) Initialize conda environments:`

### ISSUE THREAD

**Issue by Hocnonsense** [a-h-b/binny#24]
Hello, thanks for providing `binny`.

When running `./binny -i config/config.init.yaml`, I'me confusing about something:

1. Some times file `config/config.init.yaml` xabsense after running `./binny -i config/config.init.yaml`, and snakemake at line 124 failed.
2. Nowadays, `https://data.gtdb.ecogenomic.org/releases/latest/ar122_metadata.tar.gz` is unreachable because the GTDB Release 207 is now available, and `ar53` instead. Will it affect database building?
3. YAML files of conda environments are filtered in 143, but environments created by `snakemake` are all stored in `binny_initialized/conda/` according to `config/config.init.yaml` line 21. Which file should I modify and can I just cp everything from `binny_initialized/conda/` to `conda/`?

Thanks!

**Comment by ohickl** [comment]
Hey,

1. I am unsure, what you mean. `config.init.yaml` is getting deleted during setup? 
2. We will provide an update in the next days that will definitely fix point 2. This is a problem with Mantis and the change of GTDB in 207, as you already pointed out.
3. The conda environment should always be placed in the `path/to/binny/conda` (see [here](https://github.com/a-h-b/binny/blob/ba4a8d35a6020204f1d38b0fd59ef788e2809360/runscripts/binny_submit.sh#L124-L125)).
There sould not be any other `conda` dirs. Maybe you accidentally ran the init step not from the binny main dir? Either way, I would do a fresh install of the envs to be sure, although it might work just copying everything over, since binny atm always expects the envs to be in `conda/`.

Thank you for your interest (and patience)!

**Comment by Hocnonsense** [comment]
Thanks for your reply.

By the way, I realize that `3.` occurs may because I run snake maunally like 
`snakemake  --verbose --cores 1 -s Snakefile --conda-create-envs-only --use-conda --conda-prefix conda --local-cores 1 --configfile config/config.init.yaml`
, and all outputs are stored there.

**Comment by ohickl** [comment]
Ah, makes sense, since we set:
 ```
workdir:
    OUTPUTDIR
```
so using the relative path for `--conda-prefix conda` with this call will indeed result in `binny_initialized/conda/`.
You could use an absolute path for `--conda-prefix` to avoid that.

**Comment by ohickl** [comment]
Hey,
we have released a new version that should fix your issue. Feel free to give it a try!
